### ISSUE TITLE
Listening for errors

### ISSUE THREAD

**Issue by william-vw** [eyereasoner/eye-js#114]
How can one catch errors thrown by eye-js? It seems they are directly logged using `console.warn` but I'd like to show them to the user.

```ts
eyereasoner.n3reasoner(
    "abc",
    undefined,
    { output: 'derivations' }
)
.then((success) => console.log(success))
.catch((error) => console.log(error)); // not catching anything

**Comment by jeswr** [comment]
Thanks for reporting; I agree that in this instance throwing errors rather than logging them would be the best behavior.

The reason for the current behavior is that under the hood `SWIPL` is programmed to write to `stdout.err` which is mapped to a `console.warn`. What we should be doing is hooking into the `printErr` event [here](https://github.com/eyereasoner/eye-js/blob/b8ab08134b41c60de75ada08cdb19c124bc8358c/lib/transformers.ts#L131) and throwing when an error occurs.

Since this is a breaking change I'll try and release the change with https://github.com/eyereasoner/eye-js/pull/110 if I can see any notable breaking changes coming out of that PR.

**Comment by smessie** [comment]
I had the exact same question/request as the OP before 😄

> Do you see any reason to also provide access to this error-via-logging behavior (perhaps via an options parameter).

Well, as it is now, it is easier to just report the error the same way as the output is passed, e.g. in https://reasoner.smessie.com the error is also printed to the user with no extra work for the developer. However, this should not necessarily mean that this is the best way to do. Nevertheless, having the possibility might always be nice, for example for this use case.

**Comment by william-vw** [comment]
@jeswr maybe I'm misunderstanding something, but I'm pulling in the latest eye-js version (using https://eyereasoner.github.io/eye-js/2/latest/index.js) and errors are still being printed using console.warn: 
https://n3-editor.herokuapp.com/n3/editor/s/1hgaJfON (select eye-js in dropdown below execute button)

**Comment by jeswr** [comment]
The warn was changed to an error in v3.0.0. The link you have points to the latest in the v2.x.x version range.

So https://eyereasoner.github.io/eye-js/3/latest/index.js or https://eyereasoner.github.io/eye-js/latest/index.js will work.

I recommend the first one so your app doesn't suddenly break when we make a new major version.
