### ISSUE TITLE
Rule chaining not working when data and rules graphs are separated

### ISSUE THREAD

**Issue by tpluscode** [eyereasoner/eye-js#186]
When passing data graph and query graph as two arguments, rule chaining doe not work. The [example from n3 spec](https://n3-editor.herokuapp.com/n3/editor/s/LzrjNCZu) works fine but when passed to the reasoner as two arguments, only the first rule produces derivations. The same when inputs are RDF/JS quads

```js
const { n3reasoner } = require('eyereasoner')

await n3reasoner(`
    @prefix foaf: <http://xmlns.com/foaf/0.1/> .
    @prefix : <http://example.org/#>.

    :spiderman a :WebSlinger .
    :44th :traffic :heavy .
`, `
    @prefix foaf: <http://xmlns.com/foaf/0.1/> .
    @prefix : <http://example.org/#>.

    { ?slinger a :WebSlinger } => { ?slinger :locomotion :flying } .

    { ?heli a :Helicopter } => { ?heli :locomotion :flying  } .

    { ?flyer :locomotion :flying . ?street :traffic :heavy } 
      =>  { ?street :suitable-observer ?flyer } . 
`)
```

https://runkit.com/embed/nqr3titrn3qk

**Comment by jeswr** [comment]
I think this is expected behavior - the second query argument is passed to eye with the `--query` [CLI flag](https://github.com/eyereasoner/eye/blob/master/documentation/command_line.md). Data given with this flag defines individual queries to run over the data *after* derivations have been produced. I believe that these queries are evaluated once individually and then the union of their results is taken.

To have rules chained they *must* be included in the data. 

cc @josd

**Comment by josd** [comment]
Yes that is right @jeswr
